//! In-process Raft network for tests: route RPCs by direct `Raft` handle call.
//!
//! No sockets, no serialization. A registry maps (shard, node) → the live
//! `Raft` handle; an outgoing RPC clones the target handle out of the registry
//! (lock released before await) and invokes the corresponding handler. A
//! missing target maps to `Unreachable`, so a shut-down node looks like a
//! network partition to the rest of the cluster — which is what the
//! leader-failure test relies on.

// openraft's `RaftNetwork`/`RaftNetworkFactory` trait methods return
// `Result<_, RPCError<..>>` by contract; `RPCError` is a large enum (>256 B) and
// we cannot box it without violating the trait signature. The error path is
// cold (only on RPC failure), so the large-Result size is irrelevant here.
#![allow(clippy::result_large_err)]

use std::collections::HashMap;
use std::sync::{Arc, Mutex};

use openraft::error::{InstallSnapshotError, RPCError, RaftError, RemoteError, Unreachable};
use openraft::network::{RPCOption, RaftNetwork, RaftNetworkFactory};
use openraft::raft::{
    AppendEntriesRequest, AppendEntriesResponse, InstallSnapshotRequest, InstallSnapshotResponse,
    VoteRequest, VoteResponse,
};

use crate::router::ShardId;
use ledge_raft::{Node, NodeId, TypeConfig};

/// Live `Raft` handle for one (shard, node) replica.
type RaftHandle = openraft::Raft<TypeConfig>;

/// An RPC-side error addressed to a peer (`RaftError<NodeId>` payload).
type NetRpcError = RPCError<NodeId, Node, RaftError<NodeId>>;

/// An install-snapshot RPC-side error (carries `InstallSnapshotError`).
type SnapRpcError = RPCError<NodeId, Node, RaftError<NodeId, InstallSnapshotError>>;

/// Shared registry of all replicas reachable over this in-process network.
#[derive(Clone, Default)]
pub struct Registry {
    inner: Arc<Mutex<HashMap<(ShardId, NodeId), RaftHandle>>>,
}

impl Registry {
    pub fn new() -> Self {
        Self::default()
    }

    /// Register a replica's handle. Called by `testkit` after `Raft::new`,
    /// before membership `initialize`, and again on node restart.
    pub fn register(&self, shard: ShardId, node: NodeId, raft: RaftHandle) {
        self.inner.lock().unwrap().insert((shard, node), raft);
    }

    /// Remove a replica (simulating a crash / hard partition). After this,
    /// peers see the node as `Unreachable`.
    pub fn deregister(&self, shard: ShardId, node: NodeId) {
        self.inner.lock().unwrap().remove(&(shard, node));
    }

    /// Clone the target handle out (lock released on return — caller awaits
    /// the RPC without holding the lock). `None` ⇒ target down / unregistered.
    fn lookup(&self, shard: ShardId, node: NodeId) -> Option<RaftHandle> {
        self.inner.lock().unwrap().get(&(shard, node)).cloned()
    }
}

/// Build an `Unreachable` RPC error for a down/unregistered target. openraft
/// only needs *an* `Unreachable` to drive backoff + retry; the `io::Error` is a
/// marker.
fn unreachable() -> Unreachable {
    let io = std::io::Error::new(std::io::ErrorKind::ConnectionRefused, "node down");
    Unreachable::new(&io)
}

/// Per-node factory: hands out `MemConnection`s for this node's shard,
/// closing over the shared registry.
#[derive(Clone)]
pub struct MemNetworkFactory {
    shard: ShardId,
    registry: Registry,
}

impl MemNetworkFactory {
    pub fn new(shard: ShardId, registry: Registry) -> Self {
        Self { shard, registry }
    }
}

impl RaftNetworkFactory<TypeConfig> for MemNetworkFactory {
    type Network = MemConnection;

    // VERIFIED 0.9.24: async fn new_client(&mut self, target, node: &Node) -> Self::Network
    async fn new_client(&mut self, target: NodeId, _node: &Node) -> Self::Network {
        MemConnection {
            shard: self.shard,
            target,
            registry: self.registry.clone(),
        }
    }
}

/// One logical connection to `target` within `shard`. Holds no real socket;
/// resolves the target handle from the registry on each RPC.
pub struct MemConnection {
    shard: ShardId,
    target: NodeId,
    registry: Registry,
}

impl MemConnection {
    /// Resolve the target handle or produce an `Unreachable` RPC error
    /// (target crashed / not registered).
    fn target_or_unreachable(&self) -> Result<RaftHandle, NetRpcError> {
        self.registry
            .lookup(self.shard, self.target)
            .ok_or_else(|| RPCError::Unreachable(unreachable()))
    }
}

// VERIFIED 0.9.24: RaftNetwork is generated by openraft's add_async_trait, so
// impls use plain `async fn` (Send is added by the macro). Methods take
// &mut self + RPCOption. Without `generic-snapshot-data`, install_snapshot is a
// REQUIRED method; full_snapshot keeps its default (chunks through it).
impl RaftNetwork<TypeConfig> for MemConnection {
    async fn append_entries(
        &mut self,
        rpc: AppendEntriesRequest<TypeConfig>,
        _option: RPCOption,
    ) -> Result<AppendEntriesResponse<NodeId>, NetRpcError> {
        let target = self.target_or_unreachable()?;
        // Same TypeConfig on both ends → pass through, no re-serialization.
        target
            .append_entries(rpc)
            .await
            // Local handler's RaftError becomes a RemoteError on the wire side.
            .map_err(|e| RPCError::RemoteError(RemoteError::new(self.target, e)))
    }

    async fn vote(
        &mut self,
        rpc: VoteRequest<NodeId>,
        _option: RPCOption,
    ) -> Result<VoteResponse<NodeId>, NetRpcError> {
        let target = self.target_or_unreachable()?;
        target
            .vote(rpc)
            .await
            .map_err(|e| RPCError::RemoteError(RemoteError::new(self.target, e)))
    }

    async fn install_snapshot(
        &mut self,
        rpc: InstallSnapshotRequest<TypeConfig>,
        _option: RPCOption,
    ) -> Result<InstallSnapshotResponse<NodeId>, SnapRpcError> {
        let target = self
            .registry
            .lookup(self.shard, self.target)
            .ok_or_else(|| RPCError::Unreachable(unreachable()))?;
        target
            .install_snapshot(rpc)
            .await
            .map_err(|e| RPCError::RemoteError(RemoteError::new(self.target, e)))
    }
}
