// Code generated by capnpc-go. DO NOT EDIT.

package ledgepb

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	strconv "strconv"
)

type ObjectId capnp.Struct

// ObjectId_TypeID is the unique identifier for the type ObjectId.
const ObjectId_TypeID = 0xbe4e33ce61cbef0c

func NewObjectId(s *capnp.Segment) (ObjectId, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ObjectId(st), err
}

func NewRootObjectId(s *capnp.Segment) (ObjectId, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ObjectId(st), err
}

func ReadRootObjectId(msg *capnp.Message) (ObjectId, error) {
	root, err := msg.Root()
	return ObjectId(root.Struct()), err
}

func (s ObjectId) String() string {
	str, _ := text.Marshal(0xbe4e33ce61cbef0c, capnp.Struct(s))
	return str
}

func (s ObjectId) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ObjectId) DecodeFromPtr(p capnp.Ptr) ObjectId {
	return ObjectId(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ObjectId) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ObjectId) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ObjectId) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ObjectId) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ObjectId) Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s ObjectId) HasBytes() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ObjectId) SetBytes(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

// ObjectId_List is a list of ObjectId.
type ObjectId_List = capnp.StructList[ObjectId]

// NewObjectId creates a new list of ObjectId.
func NewObjectId_List(s *capnp.Segment, sz int32) (ObjectId_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[ObjectId](l), err
}

// ObjectId_Future is a wrapper for a ObjectId promised by a client call.
type ObjectId_Future struct{ *capnp.Future }

func (f ObjectId_Future) Struct() (ObjectId, error) {
	p, err := f.Future.Ptr()
	return ObjectId(p.Struct()), err
}

type RefEntry capnp.Struct

// RefEntry_TypeID is the unique identifier for the type RefEntry.
const RefEntry_TypeID = 0xd4487f86a9ed64b0

func NewRefEntry(s *capnp.Segment) (RefEntry, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return RefEntry(st), err
}

func NewRootRefEntry(s *capnp.Segment) (RefEntry, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return RefEntry(st), err
}

func ReadRootRefEntry(msg *capnp.Message) (RefEntry, error) {
	root, err := msg.Root()
	return RefEntry(root.Struct()), err
}

func (s RefEntry) String() string {
	str, _ := text.Marshal(0xd4487f86a9ed64b0, capnp.Struct(s))
	return str
}

func (s RefEntry) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (RefEntry) DecodeFromPtr(p capnp.Ptr) RefEntry {
	return RefEntry(capnp.Struct{}.DecodeFromPtr(p))
}

func (s RefEntry) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s RefEntry) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s RefEntry) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s RefEntry) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s RefEntry) Target() (ObjectId, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return ObjectId(p.Struct()), err
}

func (s RefEntry) HasTarget() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s RefEntry) SetTarget(v ObjectId) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewTarget sets the target field to a newly
// allocated ObjectId struct, preferring placement in s's segment.
func (s RefEntry) NewTarget() (ObjectId, error) {
	ss, err := NewObjectId(capnp.Struct(s).Segment())
	if err != nil {
		return ObjectId{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s RefEntry) Hlc() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s RefEntry) SetHlc(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s RefEntry) Version() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s RefEntry) SetVersion(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

// RefEntry_List is a list of RefEntry.
type RefEntry_List = capnp.StructList[RefEntry]

// NewRefEntry creates a new list of RefEntry.
func NewRefEntry_List(s *capnp.Segment, sz int32) (RefEntry_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1}, sz)
	return capnp.StructList[RefEntry](l), err
}

// RefEntry_Future is a wrapper for a RefEntry promised by a client call.
type RefEntry_Future struct{ *capnp.Future }

func (f RefEntry_Future) Struct() (RefEntry, error) {
	p, err := f.Future.Ptr()
	return RefEntry(p.Struct()), err
}
func (p RefEntry_Future) Target() ObjectId_Future {
	return ObjectId_Future{Future: p.Future.Field(0, nil)}
}

type NamedRef capnp.Struct

// NamedRef_TypeID is the unique identifier for the type NamedRef.
const NamedRef_TypeID = 0xd275cfe73808b0a1

func NewNamedRef(s *capnp.Segment) (NamedRef, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return NamedRef(st), err
}

func NewRootNamedRef(s *capnp.Segment) (NamedRef, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return NamedRef(st), err
}

func ReadRootNamedRef(msg *capnp.Message) (NamedRef, error) {
	root, err := msg.Root()
	return NamedRef(root.Struct()), err
}

func (s NamedRef) String() string {
	str, _ := text.Marshal(0xd275cfe73808b0a1, capnp.Struct(s))
	return str
}

func (s NamedRef) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (NamedRef) DecodeFromPtr(p capnp.Ptr) NamedRef {
	return NamedRef(capnp.Struct{}.DecodeFromPtr(p))
}

func (s NamedRef) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s NamedRef) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s NamedRef) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s NamedRef) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s NamedRef) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s NamedRef) HasName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s NamedRef) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s NamedRef) SetName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s NamedRef) Entry() (RefEntry, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return RefEntry(p.Struct()), err
}

func (s NamedRef) HasEntry() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s NamedRef) SetEntry(v RefEntry) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewEntry sets the entry field to a newly
// allocated RefEntry struct, preferring placement in s's segment.
func (s NamedRef) NewEntry() (RefEntry, error) {
	ss, err := NewRefEntry(capnp.Struct(s).Segment())
	if err != nil {
		return RefEntry{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

// NamedRef_List is a list of NamedRef.
type NamedRef_List = capnp.StructList[NamedRef]

// NewNamedRef creates a new list of NamedRef.
func NewNamedRef_List(s *capnp.Segment, sz int32) (NamedRef_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[NamedRef](l), err
}

// NamedRef_Future is a wrapper for a NamedRef promised by a client call.
type NamedRef_Future struct{ *capnp.Future }

func (f NamedRef_Future) Struct() (NamedRef, error) {
	p, err := f.Future.Ptr()
	return NamedRef(p.Struct()), err
}
func (p NamedRef_Future) Entry() RefEntry_Future {
	return RefEntry_Future{Future: p.Future.Field(1, nil)}
}

type WorkspaceInfo capnp.Struct

// WorkspaceInfo_TypeID is the unique identifier for the type WorkspaceInfo.
const WorkspaceInfo_TypeID = 0x9162cc08a65111ee

func NewWorkspaceInfo(s *capnp.Segment) (WorkspaceInfo, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return WorkspaceInfo(st), err
}

func NewRootWorkspaceInfo(s *capnp.Segment) (WorkspaceInfo, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return WorkspaceInfo(st), err
}

func ReadRootWorkspaceInfo(msg *capnp.Message) (WorkspaceInfo, error) {
	root, err := msg.Root()
	return WorkspaceInfo(root.Struct()), err
}

func (s WorkspaceInfo) String() string {
	str, _ := text.Marshal(0x9162cc08a65111ee, capnp.Struct(s))
	return str
}

func (s WorkspaceInfo) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (WorkspaceInfo) DecodeFromPtr(p capnp.Ptr) WorkspaceInfo {
	return WorkspaceInfo(capnp.Struct{}.DecodeFromPtr(p))
}

func (s WorkspaceInfo) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s WorkspaceInfo) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s WorkspaceInfo) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s WorkspaceInfo) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s WorkspaceInfo) Id() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s WorkspaceInfo) HasId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s WorkspaceInfo) IdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s WorkspaceInfo) SetId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s WorkspaceInfo) ExpiresAtMs() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s WorkspaceInfo) SetExpiresAtMs(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s WorkspaceInfo) Refs() (NamedRef_List, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return NamedRef_List(p.List()), err
}

func (s WorkspaceInfo) HasRefs() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s WorkspaceInfo) SetRefs(v NamedRef_List) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewRefs sets the refs field to a newly
// allocated NamedRef_List, preferring placement in s's segment.
func (s WorkspaceInfo) NewRefs(n int32) (NamedRef_List, error) {
	l, err := NewNamedRef_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return NamedRef_List{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}

// WorkspaceInfo_List is a list of WorkspaceInfo.
type WorkspaceInfo_List = capnp.StructList[WorkspaceInfo]

// NewWorkspaceInfo creates a new list of WorkspaceInfo.
func NewWorkspaceInfo_List(s *capnp.Segment, sz int32) (WorkspaceInfo_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return capnp.StructList[WorkspaceInfo](l), err
}

// WorkspaceInfo_Future is a wrapper for a WorkspaceInfo promised by a client call.
type WorkspaceInfo_Future struct{ *capnp.Future }

func (f WorkspaceInfo_Future) Struct() (WorkspaceInfo, error) {
	p, err := f.Future.Ptr()
	return WorkspaceInfo(p.Struct()), err
}

type Lease capnp.Struct

// Lease_TypeID is the unique identifier for the type Lease.
const Lease_TypeID = 0xe8f1a9d214593ec6

func NewLease(s *capnp.Segment) (Lease, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 1})
	return Lease(st), err
}

func NewRootLease(s *capnp.Segment) (Lease, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 1})
	return Lease(st), err
}

func ReadRootLease(msg *capnp.Message) (Lease, error) {
	root, err := msg.Root()
	return Lease(root.Struct()), err
}

func (s Lease) String() string {
	str, _ := text.Marshal(0xe8f1a9d214593ec6, capnp.Struct(s))
	return str
}

func (s Lease) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Lease) DecodeFromPtr(p capnp.Ptr) Lease {
	return Lease(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Lease) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Lease) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Lease) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Lease) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Lease) Id() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Lease) HasId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Lease) IdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Lease) SetId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Lease) ExpiresAtMs() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s Lease) SetExpiresAtMs(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s Lease) CreatedAtMs() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s Lease) SetCreatedAtMs(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s Lease) Generation() uint64 {
	return capnp.Struct(s).Uint64(16)
}

func (s Lease) SetGeneration(v uint64) {
	capnp.Struct(s).SetUint64(16, v)
}

// Lease_List is a list of Lease.
type Lease_List = capnp.StructList[Lease]

// NewLease creates a new list of Lease.
func NewLease_List(s *capnp.Segment, sz int32) (Lease_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 24, PointerCount: 1}, sz)
	return capnp.StructList[Lease](l), err
}

// Lease_Future is a wrapper for a Lease promised by a client call.
type Lease_Future struct{ *capnp.Future }

func (f Lease_Future) Struct() (Lease, error) {
	p, err := f.Future.Ptr()
	return Lease(p.Struct()), err
}

type GcStats capnp.Struct

// GcStats_TypeID is the unique identifier for the type GcStats.
const GcStats_TypeID = 0xa38dbf815e5b7194

func NewGcStats(s *capnp.Segment) (GcStats, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 0})
	return GcStats(st), err
}

func NewRootGcStats(s *capnp.Segment) (GcStats, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 0})
	return GcStats(st), err
}

func ReadRootGcStats(msg *capnp.Message) (GcStats, error) {
	root, err := msg.Root()
	return GcStats(root.Struct()), err
}

func (s GcStats) String() string {
	str, _ := text.Marshal(0xa38dbf815e5b7194, capnp.Struct(s))
	return str
}

func (s GcStats) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (GcStats) DecodeFromPtr(p capnp.Ptr) GcStats {
	return GcStats(capnp.Struct{}.DecodeFromPtr(p))
}

func (s GcStats) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s GcStats) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s GcStats) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s GcStats) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s GcStats) Scanned() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s GcStats) SetScanned(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s GcStats) Reachable() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s GcStats) SetReachable(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s GcStats) Reclaimed() uint64 {
	return capnp.Struct(s).Uint64(16)
}

func (s GcStats) SetReclaimed(v uint64) {
	capnp.Struct(s).SetUint64(16, v)
}

func (s GcStats) BytesFreed() uint64 {
	return capnp.Struct(s).Uint64(24)
}

func (s GcStats) SetBytesFreed(v uint64) {
	capnp.Struct(s).SetUint64(24, v)
}

// GcStats_List is a list of GcStats.
type GcStats_List = capnp.StructList[GcStats]

// NewGcStats creates a new list of GcStats.
func NewGcStats_List(s *capnp.Segment, sz int32) (GcStats_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 32, PointerCount: 0}, sz)
	return capnp.StructList[GcStats](l), err
}

// GcStats_Future is a wrapper for a GcStats promised by a client call.
type GcStats_Future struct{ *capnp.Future }

func (f GcStats_Future) Struct() (GcStats, error) {
	p, err := f.Future.Ptr()
	return GcStats(p.Struct()), err
}

type CommitMapping capnp.Struct

// CommitMapping_TypeID is the unique identifier for the type CommitMapping.
const CommitMapping_TypeID = 0xbb196c1c02004df9

func NewCommitMapping(s *capnp.Segment) (CommitMapping, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return CommitMapping(st), err
}

func NewRootCommitMapping(s *capnp.Segment) (CommitMapping, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return CommitMapping(st), err
}

func ReadRootCommitMapping(msg *capnp.Message) (CommitMapping, error) {
	root, err := msg.Root()
	return CommitMapping(root.Struct()), err
}

func (s CommitMapping) String() string {
	str, _ := text.Marshal(0xbb196c1c02004df9, capnp.Struct(s))
	return str
}

func (s CommitMapping) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CommitMapping) DecodeFromPtr(p capnp.Ptr) CommitMapping {
	return CommitMapping(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CommitMapping) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CommitMapping) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CommitMapping) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CommitMapping) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CommitMapping) WorkspaceRef() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s CommitMapping) HasWorkspaceRef() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CommitMapping) WorkspaceRefBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s CommitMapping) SetWorkspaceRef(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s CommitMapping) DurableRef() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s CommitMapping) HasDurableRef() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s CommitMapping) DurableRefBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s CommitMapping) SetDurableRef(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// CommitMapping_List is a list of CommitMapping.
type CommitMapping_List = capnp.StructList[CommitMapping]

// NewCommitMapping creates a new list of CommitMapping.
func NewCommitMapping_List(s *capnp.Segment, sz int32) (CommitMapping_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[CommitMapping](l), err
}

// CommitMapping_Future is a wrapper for a CommitMapping promised by a client call.
type CommitMapping_Future struct{ *capnp.Future }

func (f CommitMapping_Future) Struct() (CommitMapping, error) {
	p, err := f.Future.Ptr()
	return CommitMapping(p.Struct()), err
}

type CommitOutcome capnp.Struct

// CommitOutcome_TypeID is the unique identifier for the type CommitOutcome.
const CommitOutcome_TypeID = 0xdbe23771a09345ab

func NewCommitOutcome(s *capnp.Segment) (CommitOutcome, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return CommitOutcome(st), err
}

func NewRootCommitOutcome(s *capnp.Segment) (CommitOutcome, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return CommitOutcome(st), err
}

func ReadRootCommitOutcome(msg *capnp.Message) (CommitOutcome, error) {
	root, err := msg.Root()
	return CommitOutcome(root.Struct()), err
}

func (s CommitOutcome) String() string {
	str, _ := text.Marshal(0xdbe23771a09345ab, capnp.Struct(s))
	return str
}

func (s CommitOutcome) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CommitOutcome) DecodeFromPtr(p capnp.Ptr) CommitOutcome {
	return CommitOutcome(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CommitOutcome) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CommitOutcome) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CommitOutcome) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CommitOutcome) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CommitOutcome) Target() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s CommitOutcome) HasTarget() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CommitOutcome) TargetBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s CommitOutcome) SetTarget(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s CommitOutcome) Ok() bool {
	return capnp.Struct(s).Bit(0)
}

func (s CommitOutcome) SetOk(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s CommitOutcome) Version() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s CommitOutcome) SetVersion(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

// CommitOutcome_List is a list of CommitOutcome.
type CommitOutcome_List = capnp.StructList[CommitOutcome]

// NewCommitOutcome creates a new list of CommitOutcome.
func NewCommitOutcome_List(s *capnp.Segment, sz int32) (CommitOutcome_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1}, sz)
	return capnp.StructList[CommitOutcome](l), err
}

// CommitOutcome_Future is a wrapper for a CommitOutcome promised by a client call.
type CommitOutcome_Future struct{ *capnp.Future }

func (f CommitOutcome_Future) Struct() (CommitOutcome, error) {
	p, err := f.Future.Ptr()
	return CommitOutcome(p.Struct()), err
}

type Request capnp.Struct
type Request_writeObject Request
type Request_readObject Request
type Request_fork Request
type Request_commit Request
type Request_renew Request
type Request_release Request
type Request_getWorkspace Request
type Request_Which uint16

const (
	Request_Which_writeObject    Request_Which = 0
	Request_Which_readObject     Request_Which = 1
	Request_Which_fork           Request_Which = 2
	Request_Which_commit         Request_Which = 3
	Request_Which_renew          Request_Which = 4
	Request_Which_release        Request_Which = 5
	Request_Which_getWorkspace   Request_Which = 6
	Request_Which_listWorkspaces Request_Which = 7
	Request_Which_runGc          Request_Which = 8
)

func (w Request_Which) String() string {
	const s = "writeObjectreadObjectforkcommitrenewreleasegetWorkspacelistWorkspacesrunGc"
	switch w {
	case Request_Which_writeObject:
		return s[0:11]
	case Request_Which_readObject:
		return s[11:21]
	case Request_Which_fork:
		return s[21:25]
	case Request_Which_commit:
		return s[25:31]
	case Request_Which_renew:
		return s[31:36]
	case Request_Which_release:
		return s[36:43]
	case Request_Which_getWorkspace:
		return s[43:55]
	case Request_Which_listWorkspaces:
		return s[55:69]
	case Request_Which_runGc:
		return s[69:74]

	}
	return "Request_Which(" + strconv.FormatUint(uint64(w), 10) + ")"
}

// Request_TypeID is the unique identifier for the type Request.
const Request_TypeID = 0xac6d511d4a440f9e

func NewRequest(s *capnp.Segment) (Request, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 2})
	return Request(st), err
}

func NewRootRequest(s *capnp.Segment) (Request, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 2})
	return Request(st), err
}

func ReadRootRequest(msg *capnp.Message) (Request, error) {
	root, err := msg.Root()
	return Request(root.Struct()), err
}

func (s Request) String() string {
	str, _ := text.Marshal(0xac6d511d4a440f9e, capnp.Struct(s))
	return str
}

func (s Request) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Request) DecodeFromPtr(p capnp.Ptr) Request {
	return Request(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Request) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s Request) Which() Request_Which {
	return Request_Which(capnp.Struct(s).Uint16(2))
}
func (s Request) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Request) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Request) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Request) WriteObject() Request_writeObject { return Request_writeObject(s) }

func (s Request) SetWriteObject() {
	capnp.Struct(s).SetUint16(2, 0)
}

func (s Request_writeObject) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Request_writeObject) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Request_writeObject) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Request_writeObject) GitType() uint8 {
	return capnp.Struct(s).Uint8(0)
}

func (s Request_writeObject) SetGitType(v uint8) {
	capnp.Struct(s).SetUint8(0, v)
}

func (s Request_writeObject) Content() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s Request_writeObject) HasContent() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Request_writeObject) SetContent(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

func (s Request) ReadObject() Request_readObject { return Request_readObject(s) }

func (s Request) SetReadObject() {
	capnp.Struct(s).SetUint16(2, 1)
}

func (s Request_readObject) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Request_readObject) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Request_readObject) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Request_readObject) Id() (ObjectId, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return ObjectId(p.Struct()), err
}

func (s Request_readObject) HasId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Request_readObject) SetId(v ObjectId) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewId sets the id field to a newly
// allocated ObjectId struct, preferring placement in s's segment.
func (s Request_readObject) NewId() (ObjectId, error) {
	ss, err := NewObjectId(capnp.Struct(s).Segment())
	if err != nil {
		return ObjectId{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Request) Fork() Request_fork { return Request_fork(s) }

func (s Request) SetFork() {
	capnp.Struct(s).SetUint16(2, 2)
}

func (s Request_fork) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Request_fork) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Request_fork) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Request_fork) Sources() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return capnp.TextList(p.List()), err
}

func (s Request_fork) HasSources() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Request_fork) SetSources(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewSources sets the sources field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s Request_fork) NewSources(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s Request_fork) TtlSeconds() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s Request_fork) SetTtlSeconds(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s Request) Commit() Request_commit { return Request_commit(s) }

func (s Request) SetCommit() {
	capnp.Struct(s).SetUint16(2, 3)
}

func (s Request_commit) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Request_commit) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Request_commit) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Request_commit) WorkspaceId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Request_commit) HasWorkspaceId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Request_commit) WorkspaceIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Request_commit) SetWorkspaceId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Request_commit) Mappings() (CommitMapping_List, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return CommitMapping_List(p.List()), err
}

func (s Request_commit) HasMappings() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Request_commit) SetMappings(v CommitMapping_List) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewMappings sets the mappings field to a newly
// allocated CommitMapping_List, preferring placement in s's segment.
func (s Request_commit) NewMappings(n int32) (CommitMapping_List, error) {
	l, err := NewCommitMapping_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return CommitMapping_List{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}
func (s Request) Renew() Request_renew { return Request_renew(s) }

func (s Request) SetRenew() {
	capnp.Struct(s).SetUint16(2, 4)
}

func (s Request_renew) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Request_renew) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Request_renew) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Request_renew) WorkspaceId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Request_renew) HasWorkspaceId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Request_renew) WorkspaceIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Request_renew) SetWorkspaceId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Request_renew) TtlSeconds() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s Request_renew) SetTtlSeconds(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s Request) Release() Request_release { return Request_release(s) }

func (s Request) SetRelease() {
	capnp.Struct(s).SetUint16(2, 5)
}

func (s Request_release) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Request_release) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Request_release) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Request_release) WorkspaceId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Request_release) HasWorkspaceId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Request_release) WorkspaceIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Request_release) SetWorkspaceId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Request) GetWorkspace() Request_getWorkspace { return Request_getWorkspace(s) }

func (s Request) SetGetWorkspace() {
	capnp.Struct(s).SetUint16(2, 6)
}

func (s Request_getWorkspace) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Request_getWorkspace) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Request_getWorkspace) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Request_getWorkspace) WorkspaceId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Request_getWorkspace) HasWorkspaceId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Request_getWorkspace) WorkspaceIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Request_getWorkspace) SetWorkspaceId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Request) SetListWorkspaces() {
	capnp.Struct(s).SetUint16(2, 7)

}

func (s Request) SetRunGc() {
	capnp.Struct(s).SetUint16(2, 8)

}

// Request_List is a list of Request.
type Request_List = capnp.StructList[Request]

// NewRequest creates a new list of Request.
func NewRequest_List(s *capnp.Segment, sz int32) (Request_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 2}, sz)
	return capnp.StructList[Request](l), err
}

// Request_Future is a wrapper for a Request promised by a client call.
type Request_Future struct{ *capnp.Future }

func (f Request_Future) Struct() (Request, error) {
	p, err := f.Future.Ptr()
	return Request(p.Struct()), err
}
func (p Request_Future) WriteObject() Request_writeObject_Future {
	return Request_writeObject_Future{p.Future}
}

// Request_writeObject_Future is a wrapper for a Request_writeObject promised by a client call.
type Request_writeObject_Future struct{ *capnp.Future }

func (f Request_writeObject_Future) Struct() (Request_writeObject, error) {
	p, err := f.Future.Ptr()
	return Request_writeObject(p.Struct()), err
}
func (p Request_Future) ReadObject() Request_readObject_Future {
	return Request_readObject_Future{p.Future}
}

// Request_readObject_Future is a wrapper for a Request_readObject promised by a client call.
type Request_readObject_Future struct{ *capnp.Future }

func (f Request_readObject_Future) Struct() (Request_readObject, error) {
	p, err := f.Future.Ptr()
	return Request_readObject(p.Struct()), err
}
func (p Request_readObject_Future) Id() ObjectId_Future {
	return ObjectId_Future{Future: p.Future.Field(0, nil)}
}
func (p Request_Future) Fork() Request_fork_Future { return Request_fork_Future{p.Future} }

// Request_fork_Future is a wrapper for a Request_fork promised by a client call.
type Request_fork_Future struct{ *capnp.Future }

func (f Request_fork_Future) Struct() (Request_fork, error) {
	p, err := f.Future.Ptr()
	return Request_fork(p.Struct()), err
}
func (p Request_Future) Commit() Request_commit_Future { return Request_commit_Future{p.Future} }

// Request_commit_Future is a wrapper for a Request_commit promised by a client call.
type Request_commit_Future struct{ *capnp.Future }

func (f Request_commit_Future) Struct() (Request_commit, error) {
	p, err := f.Future.Ptr()
	return Request_commit(p.Struct()), err
}
func (p Request_Future) Renew() Request_renew_Future { return Request_renew_Future{p.Future} }

// Request_renew_Future is a wrapper for a Request_renew promised by a client call.
type Request_renew_Future struct{ *capnp.Future }

func (f Request_renew_Future) Struct() (Request_renew, error) {
	p, err := f.Future.Ptr()
	return Request_renew(p.Struct()), err
}
func (p Request_Future) Release() Request_release_Future { return Request_release_Future{p.Future} }

// Request_release_Future is a wrapper for a Request_release promised by a client call.
type Request_release_Future struct{ *capnp.Future }

func (f Request_release_Future) Struct() (Request_release, error) {
	p, err := f.Future.Ptr()
	return Request_release(p.Struct()), err
}
func (p Request_Future) GetWorkspace() Request_getWorkspace_Future {
	return Request_getWorkspace_Future{p.Future}
}

// Request_getWorkspace_Future is a wrapper for a Request_getWorkspace promised by a client call.
type Request_getWorkspace_Future struct{ *capnp.Future }

func (f Request_getWorkspace_Future) Struct() (Request_getWorkspace, error) {
	p, err := f.Future.Ptr()
	return Request_getWorkspace(p.Struct()), err
}

type Response capnp.Struct
type Response_Which uint16

const (
	Response_Which_error          Response_Which = 0
	Response_Which_objectId       Response_Which = 1
	Response_Which_objectContent  Response_Which = 2
	Response_Which_workspace      Response_Which = 3
	Response_Which_commitOutcomes Response_Which = 4
	Response_Which_lease          Response_Which = 5
	Response_Which_ok             Response_Which = 6
	Response_Which_workspaceList  Response_Which = 7
	Response_Which_gcStats        Response_Which = 8
)

func (w Response_Which) String() string {
	const s = "errorobjectIdobjectContentworkspacecommitOutcomesleaseokworkspaceListgcStats"
	switch w {
	case Response_Which_error:
		return s[0:5]
	case Response_Which_objectId:
		return s[5:13]
	case Response_Which_objectContent:
		return s[13:26]
	case Response_Which_workspace:
		return s[26:35]
	case Response_Which_commitOutcomes:
		return s[35:49]
	case Response_Which_lease:
		return s[49:54]
	case Response_Which_ok:
		return s[54:56]
	case Response_Which_workspaceList:
		return s[56:69]
	case Response_Which_gcStats:
		return s[69:76]

	}
	return "Response_Which(" + strconv.FormatUint(uint64(w), 10) + ")"
}

// Response_TypeID is the unique identifier for the type Response.
const Response_TypeID = 0x869a20569e443a52

func NewResponse(s *capnp.Segment) (Response, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Response(st), err
}

func NewRootResponse(s *capnp.Segment) (Response, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Response(st), err
}

func ReadRootResponse(msg *capnp.Message) (Response, error) {
	root, err := msg.Root()
	return Response(root.Struct()), err
}

func (s Response) String() string {
	str, _ := text.Marshal(0x869a20569e443a52, capnp.Struct(s))
	return str
}

func (s Response) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Response) DecodeFromPtr(p capnp.Ptr) Response {
	return Response(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Response) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s Response) Which() Response_Which {
	return Response_Which(capnp.Struct(s).Uint16(0))
}
func (s Response) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Response) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Response) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Response) Error() (string, error) {
	if capnp.Struct(s).Uint16(0) != 0 {
		panic("Which() != error")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Response) HasError() bool {
	if capnp.Struct(s).Uint16(0) != 0 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Response) ErrorBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Response) SetError(v string) error {
	capnp.Struct(s).SetUint16(0, 0)
	return capnp.Struct(s).SetText(0, v)
}

func (s Response) ObjectId() (ObjectId, error) {
	if capnp.Struct(s).Uint16(0) != 1 {
		panic("Which() != objectId")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return ObjectId(p.Struct()), err
}

func (s Response) HasObjectId() bool {
	if capnp.Struct(s).Uint16(0) != 1 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Response) SetObjectId(v ObjectId) error {
	capnp.Struct(s).SetUint16(0, 1)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewObjectId sets the objectId field to a newly
// allocated ObjectId struct, preferring placement in s's segment.
func (s Response) NewObjectId() (ObjectId, error) {
	capnp.Struct(s).SetUint16(0, 1)
	ss, err := NewObjectId(capnp.Struct(s).Segment())
	if err != nil {
		return ObjectId{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Response) ObjectContent() ([]byte, error) {
	if capnp.Struct(s).Uint16(0) != 2 {
		panic("Which() != objectContent")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s Response) HasObjectContent() bool {
	if capnp.Struct(s).Uint16(0) != 2 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Response) SetObjectContent(v []byte) error {
	capnp.Struct(s).SetUint16(0, 2)
	return capnp.Struct(s).SetData(0, v)
}

func (s Response) Workspace() (WorkspaceInfo, error) {
	if capnp.Struct(s).Uint16(0) != 3 {
		panic("Which() != workspace")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return WorkspaceInfo(p.Struct()), err
}

func (s Response) HasWorkspace() bool {
	if capnp.Struct(s).Uint16(0) != 3 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Response) SetWorkspace(v WorkspaceInfo) error {
	capnp.Struct(s).SetUint16(0, 3)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewWorkspace sets the workspace field to a newly
// allocated WorkspaceInfo struct, preferring placement in s's segment.
func (s Response) NewWorkspace() (WorkspaceInfo, error) {
	capnp.Struct(s).SetUint16(0, 3)
	ss, err := NewWorkspaceInfo(capnp.Struct(s).Segment())
	if err != nil {
		return WorkspaceInfo{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Response) CommitOutcomes() (CommitOutcome_List, error) {
	if capnp.Struct(s).Uint16(0) != 4 {
		panic("Which() != commitOutcomes")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return CommitOutcome_List(p.List()), err
}

func (s Response) HasCommitOutcomes() bool {
	if capnp.Struct(s).Uint16(0) != 4 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Response) SetCommitOutcomes(v CommitOutcome_List) error {
	capnp.Struct(s).SetUint16(0, 4)
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewCommitOutcomes sets the commitOutcomes field to a newly
// allocated CommitOutcome_List, preferring placement in s's segment.
func (s Response) NewCommitOutcomes(n int32) (CommitOutcome_List, error) {
	capnp.Struct(s).SetUint16(0, 4)
	l, err := NewCommitOutcome_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return CommitOutcome_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s Response) Lease() (Lease, error) {
	if capnp.Struct(s).Uint16(0) != 5 {
		panic("Which() != lease")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return Lease(p.Struct()), err
}

func (s Response) HasLease() bool {
	if capnp.Struct(s).Uint16(0) != 5 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Response) SetLease(v Lease) error {
	capnp.Struct(s).SetUint16(0, 5)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewLease sets the lease field to a newly
// allocated Lease struct, preferring placement in s's segment.
func (s Response) NewLease() (Lease, error) {
	capnp.Struct(s).SetUint16(0, 5)
	ss, err := NewLease(capnp.Struct(s).Segment())
	if err != nil {
		return Lease{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Response) SetOk() {
	capnp.Struct(s).SetUint16(0, 6)

}

func (s Response) WorkspaceList() (WorkspaceInfo_List, error) {
	if capnp.Struct(s).Uint16(0) != 7 {
		panic("Which() != workspaceList")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return WorkspaceInfo_List(p.List()), err
}

func (s Response) HasWorkspaceList() bool {
	if capnp.Struct(s).Uint16(0) != 7 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Response) SetWorkspaceList(v WorkspaceInfo_List) error {
	capnp.Struct(s).SetUint16(0, 7)
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewWorkspaceList sets the workspaceList field to a newly
// allocated WorkspaceInfo_List, preferring placement in s's segment.
func (s Response) NewWorkspaceList(n int32) (WorkspaceInfo_List, error) {
	capnp.Struct(s).SetUint16(0, 7)
	l, err := NewWorkspaceInfo_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return WorkspaceInfo_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s Response) GcStats() (GcStats, error) {
	if capnp.Struct(s).Uint16(0) != 8 {
		panic("Which() != gcStats")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return GcStats(p.Struct()), err
}

func (s Response) HasGcStats() bool {
	if capnp.Struct(s).Uint16(0) != 8 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Response) SetGcStats(v GcStats) error {
	capnp.Struct(s).SetUint16(0, 8)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewGcStats sets the gcStats field to a newly
// allocated GcStats struct, preferring placement in s's segment.
func (s Response) NewGcStats() (GcStats, error) {
	capnp.Struct(s).SetUint16(0, 8)
	ss, err := NewGcStats(capnp.Struct(s).Segment())
	if err != nil {
		return GcStats{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Response_List is a list of Response.
type Response_List = capnp.StructList[Response]

// NewResponse creates a new list of Response.
func NewResponse_List(s *capnp.Segment, sz int32) (Response_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[Response](l), err
}

// Response_Future is a wrapper for a Response promised by a client call.
type Response_Future struct{ *capnp.Future }

func (f Response_Future) Struct() (Response, error) {
	p, err := f.Future.Ptr()
	return Response(p.Struct()), err
}
func (p Response_Future) ObjectId() ObjectId_Future {
	return ObjectId_Future{Future: p.Future.Field(0, nil)}
}
func (p Response_Future) Workspace() WorkspaceInfo_Future {
	return WorkspaceInfo_Future{Future: p.Future.Field(0, nil)}
}
func (p Response_Future) Lease() Lease_Future {
	return Lease_Future{Future: p.Future.Field(0, nil)}
}
func (p Response_Future) GcStats() GcStats_Future {
	return GcStats_Future{Future: p.Future.Field(0, nil)}
}

const schema_bd4b7bd278003348 = "x\xda\x9cVol\x1bg\x19\x7f\x9e\xf7\xb5}vb" +
	"\xd79\xce\x134\xea\xf0V\x15\xa9\xad\xd8\xd45 \xa0" +
	"ts\x9a6,)\xc9\x92\xd7\x0e\xa0\xae\xe5\xcf\xf9\xfc" +
	"\xdaub\xfb\x9c\xbb3i\x8aF\xd8\x87\x0d\x81\xd4\x0f" +
	"\x88!\x8dIL\xe3\x8f\x80\x15\xaa\x8d\x0f\xfd\xd0\xa11" +
	"\x14i\x08\x04l(\xe2\xcb\x84\x90`\x12j\x89\x14`" +
	"\x03\xc4\xban\x1cz\xce\xf6\xdd\xc5\xb1!\xe2\xdb\xeb\xf7" +
	"y\xfc\xfc\xfd\xfd~\xef\x1d9\x11\x19\x8f\xdc\x93\xca)" +
	"\xc0\xc4B4\xe6\xe6\x8f\x9dz\xf2\xe3w<\xf1(\x88" +
	"4\xe2\xad\xa9\xb1\x0b\x1b\x9f\xfb\xe8\xf3\x93\xa8$\x00\xb4" +
	"G\xf8\xbav\x89+\x00c_\xe2.\x02\xba\x7fQ\xc5" +
	"w\xe3\xbf*~e\x9bs\x94)\x00\xda\xf3\xd1M\xed" +
	"\x17Q:\xbd\x18}\x06\xd0\xbd\xbc\xef\xc0}g\xc6_" +
	"x\x0c\xc4;\x91\xb9O\xa6O\x9d\xbe]\xd4\x7f\x08\xb7" +
	"1\x05\x01\xb4\xe5\xd8&\xa0\xd6\x8a\xad\x00\xba\x1f\xfe\xe3" +
	"\xf7\xdf\xbd\xef\xa7\x97\x1f\xef\xef\xf9J\xecM@\xed\xf7" +
	"\xb1\x1c\xa0\xfb\xd8\xf2\xd9O=\xfc\xc2\xa5oS\xfaH" +
	"7}\x84r\xa2\xf2\x9c\x96P\xe8\x14U\xae\x03\x06Q" +
	"D\x1a\x99\xdf\x15S\x12\x88\xda\x9f\x94\xe7\xb4-\xf2\x1d" +
	"\xfb\xb3\xe2u\xf5\xeb\xfd\xad\xaf?\xf5\xe5\xc9g\xfa\x17" +
	"\xf0\xfe\xc4\xeb\x80\xda\x87\x12+\x80\xb7n\xce\xb2}\xb5" +
	"\xbd?V\xd3=\xcd_Ilj\xd7\x12t\xbaJ~" +
	"n\xf2\xaf\xbf\xd4_\x1a{\xe0'\x10\xf6D\xb2\xef\x1d" +
	"Z\xd7\xee\x1c\xa2\xd3\xedC\xd4\xd2\xcf\xff\xfex\xf9\xe2" +
	"\xf7\xce\xbd\xd4?\xf7\xbdC\xaf\x02j'\x86(\xe67" +
	"\x9f\x8d\x7f\xf0\xfa\xcb\xad\x0d\xd8\x91\xfdGC\xeb\xda5" +
	"/\xe6U\xcf\xf3\xd9\xd2\xd6\xd3\x8f\xaeM\xfdv[\xf3" +
	"\xed\xf4\xea\xf0\xba\xb6w\x98N\xb7\x0d\xd3\x96~0\xf9" +
	"\xd5\xa7\x96?\xf0\xea\xef\xfa\xb8^\x19\xde\xd4\xaey\xae" +
	"W=\xd7\xdf\xc4\xbesv\xe5[\x9f\xbf\xd1\xb7\xd2\xb1" +
	"\xd9\xe4~\x04\xd4>\x96\xa4\xa6~v\xdf\x99\xcc\xc6\xd3" +
	"\xaf\xdd\xa0\xa8|{\xd4\xd5\xe4e\xed\xe1$\x9d\x1eJ" +
	"^\x07|{\xfce\xbd^\x1a}\xbdo\xccO\xa6\xde" +
	"A1e\x8abn|\xf1\xec7\xfe\xf0\xc4\xe2?\xfb" +
	"\xa7\x7f$5J\xae\x97R+p\x97[\x93\xa5\x8a\xfc" +
	"t\xc5dw\x1bz\xb3\xd1<\x96\x97v\xd3l\xd8\x12" +
	"\xe6\x11\xc5\x01\x1eI\xban\x04\x01\xd4\xad\xa3\x00\xe2\x06" +
	"G\xf1\x0f\x86)\xfc\xb7\x9bA\xba}\xed4\x80\xf8\x1b" +
	"G\xf1\x16\xc3\x14{\xdb\xcd \x03PoZ\x00\xe2\x0d" +
	"\x8e\x85\x082L\xf1\xb7\xdc\x0cr\xc2\x1d\xe6\x01\xf2\xc8" +
	"\xb1\x90\xa4\xfb\xc8-7\x83\x11\x00-\x81\x17\x01\x0aq" +
	"2\x1c C\xf4M7\x83Q\x00\xedN<\x0aP\xd8" +
	"G\x86\x83d\x88\xddt3\x18\x03\xd0\xde\x83\xa3\x00\x85" +
	";\xc8\xf0^2(o\xb8\x19ob\x87\xd0\x02(\x1c" +
	"$\xc3)2\xc4\xff\xe5f0\x0e\xa0\x9d\xc0\x09\x80\xc2" +
	"q2L!\xc3\xac\xb4,\xd3\xc2$0L\x02\xbaf" +
	"qQ\x1a\xcet\x09\x00p$\x00$ \x8e\xf8\xd6\x93" +
	"&d\x1b\x8el8\x98\x02\x86)@w\xc5\xb4\x96\xec" +
	"\xa6n\x00J\x1c\x09\xe8\xde\xf9\x97a\xd6\xebUg\xae" +
	"\x059\xc70\xeb\xd2\xc6=\x80\xf3\x1cq$\xc0\x11 " +
	"]fkR\xb7)\x82\x8f\x84v\x04n.A,H" +
	"\x92\x953U\xdb\x09\xa2\x84\xf3\xed\x01\\\xab\x18\x05G" +
	"wl\x1c\x09\x98\xdf\xa9\xa4w\xc5\x9f\xe8\x84\x94\xe9\xe9" +
	"F\xd9\xa4='y\x04\xc0[\xf3\xe4(\x80\x18\xe7(" +
	"f\x18\"\xb6\x97<]\x04\x10S\x1c\xc5\x02C\x95a" +
	"{\xc7\xe20\x80\x98\xe1(\xce3\xe4\xd5\x92?Jy" +
	"\xa1Y\xb5\xa4}\x02\x14g\xd6\xc6\x040L\x00\xa6-" +
	"Y\x0e\x0d\xc0gg\xbb\xf4>\x18\\nI\xdb\xb9\xdb" +
	"J\xcb\x86\\\x11q\xaa\xce\xdb\xafz\x88J9\xc8Q" +
	"\xbc\x8f\xa1J\xf5\xc5\x01\xd4{\x1e\x04\x10G8\x8a\xe3" +
	",\xb4\x14EN\x07U9N\xad \x0d\xb3\x01\xbc\xe4" +
	"\x1758mNz+\x11\x91v\xe2\x04\x80\x9a\xa2\xc4" +
	"I\x8e\xe2]\x03st\xc3a'\xdc\xfd\xb9\xf6Fh" +
	"\xc0#\xfe\x80\xf5\x09\x00q\xae=7\xb5;a\x99\x07" +
	"\x10%\x8e\xa2I\x13f\xed\x09\xd7\xe9\xb2\xc6Q\\`" +
	"\xa8r\xeeqHmQ\xaf\x0eG\xf1\x05\x86k\xb6\xa1" +
	"7\x1a\xb2\xe47dI\xdd8\xaf\x17k\x04\xc8\xe0\xce" +
	"\xa8\xe9\xd5\xba\x04\x0c\xfc\x8a\xab\x8e\xb4?bI\xe0\xa1" +
	"?\xf7\x96\x9f\xcf\xb5\xc7\x11\xe8\x00\x86\x84E\xdd*\x02" +
	"#\x1d@_\x96\xd4W\x1e\x04F\"\x80!\xa5V_" +
	"<\x0c\x8c$\x00CO\x87z\xe5\x180\xe2?\x86\x9e" +
	">\xf5kG\x81\x11\xf71\xf4\xca\xa9\x0fM\x00#\xde" +
	"cHSU\xb9\x08\xac\xcd\xf9aB\xe2E\x001\xcf" +
	"Q\x9c\xeb\x12>\x09\xa0\x9e!\xbdZ\xe0(>C\x0b" +
	"\xb3\xaa\x8e\x9c+.\x82\"\x0d\x87\xc6T\x9a+.J" +
	"\xe0\x86\x93.\x9b\xd6R\xae\xcd\xd5\xacEp[\xb3\xda" +
	"\xdbw+\xd2\xf1\x98\x02i\xe2\x8a[\xab\xda\xdeo\xc8" +
	"y\xdc\xb1!\x96\xb5Z\x8d\xfb\x0d\x88\x0d\x04\x92\x91\xf5" +
	"\xe2v\x01\x1c\xed\x07\xe0\x18\x01\xf8t\x07\xc03\x03\xc1" +
	"U\xd7\x9b\xcdj\xa3b\x93Buy\xd4}a\x07\xb0" +
	"\xe8\xa4\x97|Vo\xa6\xe9\x9f\xb4\xc6\xb8\x8f\xc2C\x8b" +
	"=e\xe0@\x1e\xa5e^\x96\xfd:J-K/\xd6" +
	"d\x1ex\xe8\xb27\xf3\\WN)i\xc4O\x9a\xa2" +
	"\x95\xc49\x8a\x0c\xc3\xac\x87A_J\x07M\xb0\xac\x98" +
	"\xd6Rw~\x84\xffCD\x9f\x03\x1c\xc5x\xa7\xf0\x08" +
	"\x80z/\x15~\x9c\xa3\x98\"R\x98-\xcb\x08\xe4\x96" +
	"j\xdc\xb3[\x05x@\xaf\xcbR^\x96\xa1gZ\x87" +
	";I\x8f\x84\xa6u\xd7\xd1`\x84\xe9\x86^\x97\xddq" +
	"de\xc3\xb1Vq$\xf8\xb4\x18\xa0\xc3yY\x9e$" +
	"W\xe8\x91\xe0c}$x?\x808\xc5Q\xcc\x87$" +
	"xv\"\xd0\xe5\x9c\xa3[\x15\xe9\xec|\xbd\x94\xf35" +
	"\xa3\xdb\xef\xdag\xa5eW\xcd\xc6\xc0\xfeOv\xde," +
	"'MO\xd6.\xca\x1a\xddeY\x9d\xd1ps\x09\x11" +
	"\x18\xe2\x7f\xa9\x85\xf7@\xa0K\xc3\xa6\xa2\x1b\xbe$\x0f" +
	"\xfd\x7f\x92<\x93&f\xf7\x08\xf2h \xc8\xbe\x1e\x17" +
	"\xc3z\xdc\xe9\xab^\x0c\xeb1\xdb\xa9\xc7\xff\xf3\x19t" +
	"\x0dK\xea\x8e,\xf5\xdcVdCZ\xbaS\x05\xbe\x8b" +
	"qt\xc5\xcb@\xa7;\x0c*.5\x1ap\x8b\xea\xd8" +
	"\xf9\x153(`W\x1b%7\x9c0\xe6'\x02\xcc\xfb" +
	"\x90\x9f\x08 \xbfV\xa9:\x0b\xabM\x891`\x18\x03" +
	"\\3\xccm_G\xff\x09\x00\x00\xff\xff\xdc\x11K8"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_bd4b7bd278003348,
		Nodes: []uint64{
			0x869a20569e443a52,
			0x9162cc08a65111ee,
			0x94bf40593e241caa,
			0x98aac01c1ea8e13b,
			0xa38dbf815e5b7194,
			0xac6d511d4a440f9e,
			0xaf458aa0997522cd,
			0xbb196c1c02004df9,
			0xbe4e33ce61cbef0c,
			0xce5ca77a6698f3c8,
			0xd275cfe73808b0a1,
			0xd4487f86a9ed64b0,
			0xdbe23771a09345ab,
			0xe87ea2775ba406d0,
			0xe8f1a9d214593ec6,
			0xf21a646d61cf0040,
			0xf56a9ae09d5b87d2,
		},
		Compressed: true,
	})
}
