{{- if not .Values.auth.existingSecret }}
{{- if or .Values.auth.enabled .Values.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ledge.fullname" . }}-secret
  labels:
    {{- include "ledge.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.auth.enabled }}
  cluster-secret: {{ .Values.auth.clusterSecret | quote }}
  {{- if .Values.auth.bootstrapAdminToken }}
  bootstrap-admin-token: {{ .Values.auth.bootstrapAdminToken | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.tls.enabled }}
  tls.crt: {{ .Values.tls.cert | quote }}
  tls.key: {{ .Values.tls.key | quote }}
  {{- if .Values.tls.mtls }}
  ca.crt: {{ .Values.tls.ca | quote }}
  client.crt: {{ .Values.tls.clientCert | quote }}
  client.key: {{ .Values.tls.clientKey | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
